import { StageData } from '../types';

export const STAGES_DATA: StageData[] = [
  // ==========================================
  // LANTAI 1: GERBANG BAWAH & PENJARA BATA MERAH
  // ==========================================
  {
    id: 1,
    floorNumber: 1,
    name: "Lantai I: Gerbang Bawah & Penjara Bata",
    subtitle: "Lorong Bawah Tanah Benteng Wilwatikta",
    lore: "Arya Sena terbangun di lorong bawah tanah kastil benteng yang diselimuti kegelapan pekat. Lentera obor di tangannya adalah satu-satunya penuntun arah. Resi Vidyadhara mengingatkan: 'Jaga minyak lentera dan staminamu, atau kegelapan akan menyergap jiwamu!'",
    worldWidth: 3200,
    worldHeight: 700,
    startPosition: { x: 140, y: 480 },
    checkpoints: [
      {
        id: "fl1_cp1",
        name: "Prasasti Gerbang Penjara Bata",
        levelId: 1,
        x: 200,
        y: 470,
        width: 60,
        height: 90,
        activated: true,
        description: "Prasasti suci penanda gerbang bawah tanah. Cahaya obor Resi Vidyadhara menerangi kegelapan.",
        resiAdvice: "Arya Sena muridku, jangan biarkan minyak lenteramu padam! Kegelapan di benteng ini dihuni oleh bayangan kutukan. Perhatikan pula staminamu saat berlari dan menghindar."
      },
      {
        id: "fl1_cp2",
        name: "Altar Obor Lorong Barat",
        levelId: 1,
        x: 1750,
        y: 470,
        width: 60,
        height: 90,
        activated: false,
        description: "Altar suci tempat minyak obor abadi disucikan para empu Majapahit.",
        resiAdvice: "Prajurit zirah bayangan berpatroli di depan. Tunggu hingga mereka berbalik arah, atau gunakan tebasan keris saat staminamu penuh."
      }
    ],
    artifacts: [
      {
        id: "art_kudadu",
        name: "Prasasti Kudadu (1294 M)",
        floor: 1,
        x: 1100,
        y: 460,
        width: 48,
        height: 60,
        era: "1294 M • Awal Berdirinya Majapahit",
        historicalLore: "Prasasti Kudadu dikeluarkan oleh Raden Wijaya setelah dinobatkan sebagai Raja pertama Majapahit bergelar Kertarajasa Jayawardhana. Prasasti ini memuat kisah perjuangannya saat melarikan diri ke Madura dibantu Arya Wiraraja, hingga membuka Hutan Tarik di mana ditemukannya buah maja yang berasa pahit (Wilwatikta/Majapahit).",
        imageType: "prasasti",
        solved: false,
        quiz: {
          question: "Siapakah pendiri Kerajaan Majapahit yang membuka Hutan Tarik dan bergelar Kertarajasa Jayawardhana?",
          options: [
            "Raden Wijaya",
            "Hayam Wuruk",
            "Gajah Mada",
            "Jayanegara"
          ],
          correctIndex: 0,
          explanation: "Raden Wijaya adalah pendiri sekaligus raja pertama Kerajaan Majapahit (1293-1309 M) setelah berhasil mengalahkan pasukan Mongol (Tartar) dan Jayakatwang."
        }
      },
      {
        id: "art_bata_bentar",
        name: "Lempengan Arsitektur Waringin Lawang",
        floor: 1,
        x: 2350,
        y: 460,
        width: 48,
        height: 60,
        era: "Abad ke-14 M • Arsitektur Trowulan",
        historicalLore: "Candi Bentar Waringin Lawang di Trowulan adalah gerbang belah khas arsitektur Majapahit yang melambangkan terbelahnya Gunung Meru menjadi dua bagian suci (Kailasha dan Mahameru), menandakan batas sakral wilayah istana.",
        imageType: "prasasti",
        solved: false,
        quiz: {
          question: "Apakah nama bentuk gerbang belah tanpa atap penghubung khas arsitektur Majapahit seperti Waringin Lawang?",
          options: [
            "Candi Bentar",
            "Paduraksa",
            "Gapura Bajang Ratu",
            "Pendopo Agung"
          ],
          correctIndex: 0,
          explanation: "Candi Bentar adalah tipe gapura belah dua sisi tanpa atap yang menandakan pintu masuk bagian luar (nista mandala) kompleks candi atau benteng Majapahit."
        }
      }
    ],
    platforms: [
      // Floor ground
      { x: 0, y: 560, width: 3300, height: 140, type: 'brick' },
      // Elevated ruins
      { x: 420, y: 440, width: 150, height: 24, type: 'stone' },
      { x: 620, y: 350, width: 170, height: 24, type: 'brick' },
      { x: 860, y: 440, width: 140, height: 24, type: 'stone' },
      // Spikes pit
      { x: 1250, y: 550, width: 220, height: 20, type: 'spike', isHazard: true },
      { x: 1260, y: 430, width: 200, height: 24, type: 'wood' },
      // Intermediate platforms
      { x: 1550, y: 440, width: 140, height: 24, type: 'stone' },
      { x: 1950, y: 440, width: 160, height: 24, type: 'brick' },
      { x: 2150, y: 350, width: 180, height: 24, type: 'stone' },
      { x: 2480, y: 450, width: 150, height: 24, type: 'wood' },
      // Exit stairwell
      { x: 2850, y: 460, width: 260, height: 100, type: 'altar' }
    ],
    enemies: [
      {
        id: "fl1_e1",
        type: "prajurit_bayangan",
        name: "Prajurit Zirah Bayangan (Tingkat I)",
        x: 750,
        y: 490,
        vx: 0,
        vy: 0,
        width: 44,
        height: 64,
        hp: 55,
        maxHp: 55,
        damage: 12,
        direction: "left",
        state: "patrol",
        patrolLeft: 650,
        patrolRight: 950,
        detectRadius: 190,
        attackRadius: 55,
        attackCooldown: 1.6,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 8
      },
      {
        id: "fl1_e2",
        type: "pemanah_bayangan",
        name: "Pemanah Zirah Bayangan (Tingkat I)",
        x: 1600,
        y: 375,
        vx: 0,
        vy: 0,
        width: 40,
        height: 60,
        hp: 40,
        maxHp: 40,
        damage: 10,
        direction: "left",
        state: "patrol",
        patrolLeft: 1550,
        patrolRight: 1700,
        detectRadius: 260,
        attackRadius: 240,
        attackCooldown: 2.2,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 10
      },
      {
        id: "fl1_e3",
        type: "prajurit_bayangan",
        name: "Prajurit Zirah Bayangan Penjaga (Tingkat I)",
        x: 2180,
        y: 490,
        vx: 0,
        vy: 0,
        width: 44,
        height: 64,
        hp: 65,
        maxHp: 65,
        damage: 14,
        direction: "left",
        state: "patrol",
        patrolLeft: 2000,
        patrolRight: 2320,
        detectRadius: 200,
        attackRadius: 60,
        attackCooldown: 1.5,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 12
      },
      {
        id: "fl1_e4",
        type: "prajurit_bayangan",
        name: "Prajurit Zirah Bayangan Tangga (Tingkat I)",
        x: 2750,
        y: 490,
        vx: 0,
        vy: 0,
        width: 44,
        height: 64,
        hp: 70,
        maxHp: 70,
        damage: 16,
        direction: "left",
        state: "patrol",
        patrolLeft: 2600,
        patrolRight: 2880,
        detectRadius: 220,
        attackRadius: 60,
        attackCooldown: 1.4,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 15
      }
    ],
    props: [
      { x: 100, y: 460, type: 'resi_sanctuary', width: 80, height: 100 },
      { x: 450, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 880, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 1450, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 1750, y: 460, type: 'resi_sanctuary', width: 80, height: 100 },
      { x: 2100, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 2600, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 3050, y: 440, type: 'candi_gate', width: 100, height: 120 }
    ]
  },

  // ==============================================================
  // LANTAI 2: BALAIRUNG BARIKADE PERTAHANAN & FORMASI SERBUAN
  // ==============================================================
  {
    id: 2,
    floorNumber: 2,
    name: "Lantai II: Balairung Barikade Pertahanan",
    subtitle: "Peperangan Formasi Prajurit Zirah Bayangan",
    lore: "Balairung istana tengah diserbu oleh barisan formasi prajurit zirah bayangan! Di tengah balairung berdiri Barikade Pertahanan Benteng. Arya Sena harus mempertahankan barikade ini. Jika barikade benteng hancur, balairung akan tenggelam dalam kutukan bayangan!",
    worldWidth: 3400,
    worldHeight: 700,
    startPosition: { x: 120, y: 480 },
    barricade: {
      x: 1850,
      y: 450,
      width: 50,
      height: 110,
      hp: 200,
      maxHp: 200
    },
    checkpoints: [
      {
        id: "fl2_cp1",
        name: "Prasasti Pos Barikade Balairung",
        levelId: 2,
        x: 200,
        y: 470,
        width: 60,
        height: 90,
        activated: true,
        description: "Pos pertahanan bala tentara Bhayangkara. Sang Resi menenangkan sukma para prajurit.",
        resiAdvice: "Waspadalah Arya Sena! Musuh datang dalam formasi terorganisir untuk meremukkan barikade benteng di koordinat tengah. Cegat mereka sebelum mendekati barikade!"
      },
      {
        id: "fl2_cp2",
        name: "Prasasti Perlindungan Balairung Timur",
        levelId: 2,
        x: 2400,
        y: 470,
        width: 60,
        height: 90,
        activated: false,
        description: "Batu prasasti penjaga sayap timur balairung istana.",
        resiAdvice: "Kerja bagus mempertahankan barikade! Rawat staminamu dengan istirahat sejenak di samping lentera suci."
      }
    ],
    artifacts: [
      {
        id: "art_panji_bhayangkara",
        name: "Panji Dwiwarna & Tombak Bhayangkara",
        floor: 2,
        x: 1400,
        y: 460,
        width: 48,
        height: 60,
        era: "Abad ke-14 M • Korps Pengawal Elite Majapahit",
        historicalLore: "Korps Bhayangkara dibentuk oleh Mahapatih Gajah Mada sebagai pasukan elite pengawal raja dan penegak hukum Wilwatikta yang bersumpah dengan empat prinsip: Satya Haprabu (setia pada negara), Hanyaken Musuh (memusnahkan musuh negara), Gineg Pratidina (berlatih tiada henti), dan Tan Satrisna (ikhlas tanpa pamrih).",
        imageType: "panji",
        solved: false,
        quiz: {
          question: "Apakah nama sumpah kesetiaan pasukan Bhayangkara yang bermakna setia sepenuhnya kepada raja dan negara?",
          options: [
            "Satya Haprabu",
            "Tan Satrisna",
            "Hanyaken Musuh",
            "Gineg Pratidina"
          ],
          correctIndex: 0,
          explanation: "Satya Haprabu adalah doktrin utama Bhayangkara yang bermakna setia dan patuh sepenuhnya kepada pimpinan tertinggi negara/raja."
        }
      }
    ],
    platforms: [
      { x: 0, y: 560, width: 3500, height: 140, type: 'brick' },
      { x: 380, y: 440, width: 140, height: 24, type: 'stone' },
      { x: 620, y: 350, width: 180, height: 24, type: 'brick' },
      { x: 880, y: 450, width: 160, height: 24, type: 'stone' },
      // Barricade support platforms
      { x: 1600, y: 440, width: 180, height: 24, type: 'wood' },
      { x: 1950, y: 440, width: 180, height: 24, type: 'wood' },
      { x: 2150, y: 350, width: 160, height: 24, type: 'stone' },
      { x: 2600, y: 450, width: 180, height: 24, type: 'brick' },
      { x: 2950, y: 460, width: 280, height: 100, type: 'altar' }
    ],
    enemies: [
      {
        id: "fl2_e1",
        type: "prajurit_bayangan",
        name: "Prajurit Zirah Bayangan (Tingkat II)",
        x: 800,
        y: 490,
        vx: 0,
        vy: 0,
        width: 44,
        height: 64,
        hp: 75,
        maxHp: 75,
        damage: 22,
        direction: "left",
        state: "patrol",
        patrolLeft: 650,
        patrolRight: 980,
        detectRadius: 210,
        attackRadius: 55,
        attackCooldown: 1.4,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 10
      },
      {
        id: "fl2_e2",
        type: "tombak_bayangan",
        name: "Penombak Zirah Bayangan (Tingkat II)",
        x: 1700,
        y: 490,
        vx: 0,
        vy: 0,
        width: 46,
        height: 64,
        hp: 85,
        maxHp: 85,
        damage: 24,
        direction: "left",
        state: "chase",
        patrolLeft: 1600,
        patrolRight: 1900,
        detectRadius: 250,
        attackRadius: 75,
        attackCooldown: 1.5,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 15
      },
      {
        id: "fl2_e3",
        type: "prajurit_bayangan",
        name: "Prajurit Formasi Serbuan (Tingkat II)",
        x: 2050,
        y: 490,
        vx: 0,
        vy: 0,
        width: 44,
        height: 64,
        hp: 90,
        maxHp: 90,
        damage: 25,
        direction: "left",
        state: "patrol",
        patrolLeft: 1950,
        patrolRight: 2250,
        detectRadius: 240,
        attackRadius: 55,
        attackCooldown: 1.3,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 15
      },
      {
        id: "fl2_e4",
        type: "pemanah_bayangan",
        name: "Pemanah Balairung Elit (Tingkat II)",
        x: 2160,
        y: 285,
        vx: 0,
        vy: 0,
        width: 40,
        height: 60,
        hp: 55,
        maxHp: 55,
        damage: 20,
        direction: "left",
        state: "patrol",
        patrolLeft: 2140,
        patrolRight: 2280,
        detectRadius: 280,
        attackRadius: 260,
        attackCooldown: 1.9,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 12
      },
      {
        id: "fl2_e5",
        type: "prajurit_bayangan",
        name: "Komandan Zirah Formasi Balairung (Tingkat II)",
        x: 2750,
        y: 490,
        vx: 0,
        vy: 0,
        width: 50,
        height: 70,
        hp: 130,
        maxHp: 130,
        damage: 28,
        direction: "left",
        state: "patrol",
        patrolLeft: 2650,
        patrolRight: 2900,
        detectRadius: 250,
        attackRadius: 65,
        attackCooldown: 1.2,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 25
      }
    ],
    props: [
      { x: 100, y: 460, type: 'resi_sanctuary', width: 80, height: 100 },
      { x: 500, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 1100, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 1850, y: 450, type: 'barricade_prop', width: 50, height: 110 },
      { x: 2000, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 2400, y: 460, type: 'resi_sanctuary', width: 80, height: 100 },
      { x: 2800, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 3200, y: 440, type: 'candi_gate', width: 100, height: 120 }
    ]
  },

  // ==============================================================
  // LANTAI 3: PERPUSTAKAAN LONTAR KUNO & RUANG PRASASTI RAHASIA
  // ==============================================================
  {
    id: 3,
    floorNumber: 3,
    name: "Lantai III: Perpustakaan Lontar Kuno",
    subtitle: "Ruang Arsip Suci & Misteri Angkara Dahana",
    lore: "Ruang perpustakaan lontar kuno Majapahit menyimpan naskah-naskah tak ternilai harganya. Di sini, Resi Vidyadhara mengungkapkan hakikat Avatar Angkara Dahana: sebuah kutukan kuno yang lahir dari api dendam kekalahan masa lalu dan ingin menghapus seluruh jejak kejayaan nusantara.",
    worldWidth: 3200,
    worldHeight: 700,
    startPosition: { x: 120, y: 480 },
    checkpoints: [
      {
        id: "fl3_cp1",
        name: "Altar Lontar Suci Vidyadhara",
        levelId: 3,
        x: 200,
        y: 470,
        width: 60,
        height: 90,
        activated: true,
        description: "Tempat Resi Vidyadhara mendaraskan mantra pencerahan dari kitab suci lontar.",
        resiAdvice: "Mpu-mpu agung meninggalkan kebijaksanaan dalam naskah lontar. Pecahkan kuis sejarah artefak di lantai ini, maka koin pengetahuanmu akan menjadi kekuatan untuk membuka segel lantai puncak!"
      },
      {
        id: "fl3_cp2",
        name: "Prasasti Ruang Sastra Trowulan",
        levelId: 3,
        x: 1800,
        y: 470,
        width: 60,
        height: 90,
        activated: false,
        description: "Prasasti perunggu pelindung naskah lontar dari ancaman api dan bayangan gaib.",
        resiAdvice: "Avatar Angkara Dahana takut pada cahaya kebenaran dan ilmu pengetahuan. Kumpulkan seluruh koin pengetahuan artefak!"
      }
    ],
    artifacts: [
      {
        id: "art_negarakretagama",
        name: "Kakawin Negarakretagama (Desawarnana)",
        floor: 3,
        x: 1050,
        y: 460,
        width: 48,
        height: 60,
        era: "1365 M • Ditulis oleh Mpu Prapanca",
        historicalLore: "Kakawin Negarakretagama atau Desawarnana ditulis oleh Mpu Prapanca pada tahun 1365 M di masa keemasan Prabu Hayam Wuruk. Kitab lontar ini memaparkan tata susunan kota raja Majapahit, sistem birokrasi peradilan, upacara kenegaraan, serta daftar wilayah taklukan dan persahabatan di seluruh Nusantara (Mitreka Satata).",
        imageType: "lontar",
        solved: false,
        quiz: {
          question: "Siapakah sastrawan besar Majapahit yang menulis Kakawin Negarakretagama pada masa pemerintahan Raja Hayam Wuruk?",
          options: [
            "Mpu Prapanca",
            "Mpu Tantular",
            "Mpu Sedah",
            "Mpu Panuluh"
          ],
          correctIndex: 0,
          explanation: "Mpu Prapanca adalah pujangga terkemuka Majapahit yang menggubah naskah agung Negarakretagama (Desawarnana) pada tahun 1365 M."
        }
      },
      {
        id: "art_sutasoma",
        name: "Kakawin Sutasoma (Bhinneka Tunggal Ika)",
        floor: 3,
        x: 2300,
        y: 460,
        width: 48,
        height: 60,
        era: "Abad ke-14 M • Ditulis oleh Mpu Tantular",
        historicalLore: "Kakawin Sutasoma dikarang oleh Mpu Tantular pada masa pemerintahan Hayam Wuruk. Di dalam pupuh 139 bait 5 termaktub kalimat agung: 'Bhinneka Tunggal Ika Tan Hana Dharma Mangrwa', yang mengajarkan toleransi mendalam antara penganut Siwa dan Buddha di Majapahit, yang kini menjadi semboyan resmi bangsa Indonesia.",
        imageType: "lontar",
        solved: false,
        quiz: {
          question: "Apakah makna dari semboyan luhur 'Bhinneka Tunggal Ika' yang tertuang dalam Kitab Sutasoma karya Mpu Tantular?",
          options: [
            "Berbeda-beda tetapi tetap satu jua",
            "Bersatu kita teguh bercerai kita runtuh",
            "Kebenaran pasti akan mengalahkan kejahatan",
            "Kekuasaan raja tidak tertandingi"
          ],
          correctIndex: 0,
          explanation: "'Bhinneka Tunggal Ika' bermakna berbeda-beda tetapi hakikatnya tetap satu jua, menjadi pilar kebersamaan dan persatuan Nusantara."
        }
      }
    ],
    platforms: [
      { x: 0, y: 560, width: 3300, height: 140, type: 'brick' },
      { x: 350, y: 440, width: 150, height: 24, type: 'stone' },
      { x: 580, y: 350, width: 170, height: 24, type: 'brick' },
      { x: 800, y: 440, width: 140, height: 24, type: 'stone' },
      // Hazards
      { x: 1300, y: 550, width: 200, height: 20, type: 'spike', isHazard: true },
      { x: 1320, y: 430, width: 170, height: 24, type: 'wood' },
      { x: 1600, y: 440, width: 160, height: 24, type: 'stone' },
      { x: 2050, y: 440, width: 180, height: 24, type: 'brick' },
      { x: 2450, y: 360, width: 160, height: 24, type: 'stone' },
      { x: 2750, y: 450, width: 180, height: 24, type: 'wood' },
      { x: 2950, y: 460, width: 280, height: 100, type: 'altar' }
    ],
    enemies: [
      {
        id: "fl3_e1",
        type: "prajurit_bayangan",
        name: "Prajurit Kutukan Lemari Lontar (Tingkat III)",
        x: 750,
        y: 490,
        vx: 0,
        vy: 0,
        width: 44,
        height: 64,
        hp: 95,
        maxHp: 95,
        damage: 32,
        direction: "left",
        state: "patrol",
        patrolLeft: 600,
        patrolRight: 920,
        detectRadius: 210,
        attackRadius: 55,
        attackCooldown: 1.3,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 14
      },
      {
        id: "fl3_e2",
        type: "pemanah_bayangan",
        name: "Pemanah Kutukan Api Hitam (Tingkat III)",
        x: 1650,
        y: 375,
        vx: 0,
        vy: 0,
        width: 40,
        height: 60,
        hp: 75,
        maxHp: 75,
        damage: 28,
        direction: "left",
        state: "patrol",
        patrolLeft: 1600,
        patrolRight: 1750,
        detectRadius: 280,
        attackRadius: 260,
        attackCooldown: 1.8,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 16
      },
      {
        id: "fl3_e3",
        type: "tombak_bayangan",
        name: "Prajurit Tombak Kutukan Lontar (Tingkat III)",
        x: 2150,
        y: 490,
        vx: 0,
        vy: 0,
        width: 46,
        height: 64,
        hp: 110,
        maxHp: 110,
        damage: 35,
        direction: "left",
        state: "patrol",
        patrolLeft: 2000,
        patrolRight: 2280,
        detectRadius: 230,
        attackRadius: 75,
        attackCooldown: 1.4,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 20
      },
      {
        id: "fl3_e4",
        type: "prajurit_bayangan",
        name: "Pengawal Elit Altar Rahasia (Tingkat III)",
        x: 2700,
        y: 490,
        vx: 0,
        vy: 0,
        width: 48,
        height: 66,
        hp: 130,
        maxHp: 130,
        damage: 38,
        direction: "left",
        state: "patrol",
        patrolLeft: 2550,
        patrolRight: 2880,
        detectRadius: 240,
        attackRadius: 60,
        attackCooldown: 1.2,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 24
      }
    ],
    props: [
      { x: 100, y: 460, type: 'resi_sanctuary', width: 80, height: 100 },
      { x: 480, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 950, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 1450, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 1800, y: 460, type: 'resi_sanctuary', width: 80, height: 100 },
      { x: 2200, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 2650, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 3100, y: 440, type: 'candi_gate', width: 100, height: 120 }
    ]
  },

  // ==============================================================
  // LANTAI 4: LORONG ZIRAH KUTUKAN & LABIRIN PERANGKAP GAIB
  // ==============================================================
  {
    id: 4,
    floorNumber: 4,
    name: "Lantai IV: Lorong Zirah Kutukan",
    subtitle: "Labirin Perangkap Gaib & Segel Puncak",
    lore: "Kegelapan di lantai ini terasa membeku dan mencekam. Bayangan kutukan bergerak di antara reruntuhan dinding bata. Di ujung lorong, terdapat Segel Gerbang Puncak yang hanya bisa dibuka dengan mengumpulkan Koin Pengetahuan Sejarah dari artefak masa lalu.",
    worldWidth: 3300,
    worldHeight: 700,
    startPosition: { x: 120, y: 480 },
    requiredKnowledgeCoinsToAdvance: 40,
    checkpoints: [
      {
        id: "fl4_cp1",
        name: "Prasasti Altar Segel Puncak",
        levelId: 4,
        x: 200,
        y: 470,
        width: 60,
        height: 90,
        activated: true,
        description: "Tempat Resi Vidyadhara memanjatkan doa suci untuk memperkuat perisai jiwa Arya Sena.",
        resiAdvice: "Arya Sena, gerbang menuju Lantai V dijaga oleh segel purba. Engkau membutuhkan setidaknya 40 Koin Pengetahuan Sejarah untuk mendobrak segel tersebut dan menantang Avatar Angkara Dahana!"
      },
      {
        id: "fl4_cp2",
        name: "Pos Suci Lorong Segel Timur",
        levelId: 4,
        x: 1950,
        y: 470,
        width: 60,
        height: 90,
        activated: false,
        description: "Altar terakhir sebelum menapaki tangga puncak singgasana istana.",
        resiAdvice: "Avatar Angkara Dahana membara dengan amukan api purba. Ketika staminamu terkuras, menjauhlah sejenak di bawah naungan cahaya obor!"
      }
    ],
    artifacts: [
      {
        id: "art_sumpah_palapa",
        name: "Keris Pusaka & Prasasti Sumpah Palapa",
        floor: 4,
        x: 1350,
        y: 460,
        width: 48,
        height: 60,
        era: "1336 M • Pengangkatan Mahapatih Gajah Mada",
        historicalLore: "Ketika diangkat menjadi Patih Amangkubhumi pada tahun 1336 M, Gajah Mada mengikrarkan Sumpah Palapa di hadapan Ratu Tribhuwana Tunggadewi, bersumpah tidak akan menikmati istirahat atau kenikmatan duniawi (palapa) sebelum seluruh kepulauan Nusantara berhasil dipersatukan di bawah panji Wilwatikta.",
        imageType: "keris",
        solved: false,
        quiz: {
          question: "Apakah nama sumpah legendaris yang diikrarkan Mahapatih Gajah Mada untuk menyatukan Nusantara?",
          options: [
            "Sumpah Palapa",
            "Prasasti Trowulan",
            "Catur Asrama",
            "Sumpah Pasundan"
          ],
          correctIndex: 0,
          explanation: "Sumpah Palapa diikrarkan oleh Gajah Mada pada tahun 1336 M dengan tekad bulat mempersatukan pulau-pulau Nusantara di bawah naungan Majapahit."
        }
      }
    ],
    platforms: [
      { x: 0, y: 560, width: 3400, height: 140, type: 'brick' },
      { x: 380, y: 440, width: 140, height: 24, type: 'stone' },
      { x: 620, y: 340, width: 170, height: 24, type: 'brick' },
      { x: 880, y: 440, width: 150, height: 24, type: 'stone' },
      // Hazards
      { x: 1100, y: 550, width: 180, height: 20, type: 'spike', isHazard: true },
      { x: 1110, y: 430, width: 160, height: 24, type: 'wood' },
      { x: 1550, y: 440, width: 160, height: 24, type: 'stone' },
      { x: 1750, y: 350, width: 180, height: 24, type: 'brick' },
      { x: 2150, y: 440, width: 160, height: 24, type: 'stone' },
      { x: 2500, y: 440, width: 180, height: 24, type: 'wood' },
      { x: 2900, y: 460, width: 280, height: 100, type: 'altar' }
    ],
    enemies: [
      {
        id: "fl4_e1",
        type: "prajurit_bayangan",
        name: "Prajurit Zirah Neraka Hitam (Tingkat IV)",
        x: 750,
        y: 490,
        vx: 0,
        vy: 0,
        width: 44,
        height: 64,
        hp: 120,
        maxHp: 120,
        damage: 42,
        direction: "left",
        state: "patrol",
        patrolLeft: 600,
        patrolRight: 920,
        detectRadius: 220,
        attackRadius: 60,
        attackCooldown: 1.2,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 18
      },
      {
        id: "fl4_e2",
        type: "tombak_bayangan",
        name: "Prajurit Tombak Neraka Membara (Tingkat IV)",
        x: 1600,
        y: 490,
        vx: 0,
        vy: 0,
        width: 46,
        height: 64,
        hp: 135,
        maxHp: 135,
        damage: 46,
        direction: "left",
        state: "patrol",
        patrolLeft: 1450,
        patrolRight: 1780,
        detectRadius: 240,
        attackRadius: 75,
        attackCooldown: 1.3,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 22
      },
      {
        id: "fl4_e3",
        type: "pemanah_bayangan",
        name: "Pemanah Panah Beracun Neraka (Tingkat IV)",
        x: 1780,
        y: 285,
        vx: 0,
        vy: 0,
        width: 40,
        height: 60,
        hp: 85,
        maxHp: 85,
        damage: 38,
        direction: "left",
        state: "patrol",
        patrolLeft: 1760,
        patrolRight: 1900,
        detectRadius: 290,
        attackRadius: 270,
        attackCooldown: 1.7,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 20
      },
      {
        id: "fl4_e4",
        type: "prajurit_bayangan",
        name: "Senopati Garda Zirah Hitam (Panglima Puncak IV)",
        x: 2700,
        y: 490,
        vx: 0,
        vy: 0,
        width: 52,
        height: 72,
        hp: 240,
        maxHp: 240,
        damage: 54,
        direction: "left",
        state: "patrol",
        patrolLeft: 2550,
        patrolRight: 2880,
        detectRadius: 260,
        attackRadius: 65,
        attackCooldown: 1.1,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 45,
        isBoss: true
      }
    ],
    props: [
      { x: 100, y: 460, type: 'resi_sanctuary', width: 80, height: 100 },
      { x: 450, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 920, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 1400, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 1950, y: 460, type: 'resi_sanctuary', width: 80, height: 100 },
      { x: 2350, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 2750, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 3150, y: 440, type: 'candi_gate', width: 100, height: 120 }
    ]
  },

  // ==============================================================
  // LANTAI 5: PUNCAK MENARA SINGGASANA & ALTAR AVATAR ANGKARA DAHANA
  // ==============================================================
  {
    id: 5,
    floorNumber: 5,
    name: "Lantai V: Puncak Singgasana Altar Dahana",
    subtitle: "Perang Menumpas Avatar Angkara Dahana",
    lore: "Puncak tertinggi Benteng Wilwatikta telah diselimuti kobaran api merah dan kabut dendam. Avatar Angkara Dahana menanti Arya Sena di atas singgasana batu. Pertarungan pamungkas demi kedaulatan Majapahit dan kelestarian sejarah nusantara dimulai di sini!",
    worldWidth: 2600,
    worldHeight: 700,
    startPosition: { x: 140, y: 480 },
    checkpoints: [
      {
        id: "fl5_cp1",
        name: "Prasasti Altar Singgasana Puncak",
        levelId: 5,
        x: 200,
        y: 470,
        width: 60,
        height: 90,
        activated: true,
        description: "Altar sakral Surya Majapahit di puncak benteng. Resi Vidyadhara memegang panji pusaka kebenaran.",
        resiAdvice: "Arya Sena ksatria pilihan! Avatar Angkara Dahana melancarkan badai api membara. Manfaatkan lompatan dan tangkisan perisaimu dengan hemat stamina. Ketika api di tubuhnya meredup sejenak, hantamkan Keris Pusakamu!"
      }
    ],
    artifacts: [
      {
        id: "art_surya_majapahit",
        name: "Emblem Emas Surya Majapahit",
        floor: 5,
        x: 800,
        y: 460,
        width: 48,
        height: 60,
        era: "Abad ke-14 M • Lambang Resmi Kemaharajaan Wilwatikta",
        historicalLore: "Surya Majapahit adalah lambang resmi kerajaan yang menggambarkan diagram delapan arah mata angin (astadikpalaka) dengan dewa pelindung semesta (Lokapala) serta Dewa Siwa di titik pusat, melambangkan keteraturan kosmis, kemakmuran, dan kedaulatan mutlak.",
        imageType: "genta",
        solved: false,
        quiz: {
          question: "Berapa banyakkah pancaran sinar utama (arah mata angin) pada lambang keagungan Surya Majapahit?",
          options: [
            "Delapan (8)",
            "Empat (4)",
            "Enam (6)",
            "Sepuluh (10)"
          ],
          correctIndex: 0,
          explanation: "Surya Majapahit memiliki delapan (8) sinar utama yang melambangkan delapan penjuru mata angin dan dewa-dewa Lokapala penjaga alam semesta."
        }
      }
    ],
    platforms: [
      { x: 0, y: 560, width: 2700, height: 140, type: 'brick' },
      { x: 350, y: 440, width: 160, height: 24, type: 'stone' },
      { x: 600, y: 350, width: 180, height: 24, type: 'altar' },
      { x: 900, y: 440, width: 160, height: 24, type: 'stone' },
      // Boss arena elevated flanks
      { x: 1200, y: 430, width: 170, height: 24, type: 'stone' },
      { x: 1550, y: 340, width: 200, height: 24, type: 'altar' },
      { x: 1900, y: 430, width: 170, height: 24, type: 'stone' },
      // Throne platform
      { x: 2200, y: 460, width: 320, height: 100, type: 'altar' }
    ],
    enemies: [
      {
        id: "fl5_e1",
        type: "prajurit_bayangan",
        name: "Pengawal Api Dahana",
        x: 1450,
        y: 490,
        vx: 0,
        vy: 0,
        width: 44,
        height: 64,
        hp: 110,
        maxHp: 110,
        damage: 42,
        direction: "left",
        state: "patrol",
        patrolLeft: 1350,
        patrolRight: 1600,
        detectRadius: 240,
        attackRadius: 60,
        attackCooldown: 1.3,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 20
      },
      {
        id: "fl5_e2",
        type: "pemanah_bayangan",
        name: "Pemanah Panah Magma Dahana",
        x: 1650,
        y: 375,
        vx: 0,
        vy: 0,
        width: 40,
        height: 60,
        hp: 90,
        maxHp: 90,
        damage: 38,
        direction: "left",
        state: "patrol",
        patrolLeft: 1600,
        patrolRight: 1750,
        detectRadius: 280,
        attackRadius: 260,
        attackCooldown: 1.8,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 20
      },
      {
        id: "boss_angkara_dahana",
        type: "avatar_angkara_dahana",
        name: "AVATAR ANGKARA DAHANA (Raja Kejahatan)",
        x: 2050,
        y: 410,
        vx: 0,
        vy: 0,
        width: 80,
        height: 115,
        hp: 600,
        maxHp: 600,
        damage: 65,
        direction: "left",
        state: "chase",
        patrolLeft: 1100,
        patrolRight: 2400,
        detectRadius: 750,
        attackRadius: 100,
        attackCooldown: 1.5,
        attackTimer: 0,
        hurtTimer: 0,
        coinsValue: 200,
        isBoss: true,
        specialSkillTimer: 0
      }
    ],
    props: [
      { x: 100, y: 460, type: 'resi_sanctuary', width: 80, height: 100 },
      { x: 450, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 950, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 1350, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 1750, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 2100, y: 500, type: 'torch', width: 30, height: 60 },
      { x: 2400, y: 440, type: 'candi_gate', width: 100, height: 120 }
    ]
  }
];
